# Generated by Django 4.1.2 on 2022-10-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
